### ISSUE TITLE
Documentation Gap: Using SummerBatchCore with netstandard

### ISSUE THREAD

**Issue by drobert-bfm** [SummerBatch/SummerBatchCore#2]
The documentation shows the use of Unity for dependency injection, but Unity < 5.0.0 does not work on netstandard, and Unity 5+ is not compatible with SummerBatchCore due to a difference in namespaces. 

Please update the documentation to provide proper instructions for the use of SummerBatchCore in a non-.Net Framework environment, or better yet, update the code to use native DI or Unity 5.

**Comment by erik75269** [comment]
Unity.NetCore is compatible with SummerBatchCore now. You can see more detail in the [Getting started guide - SummerBatchCore](https://www.bluage.com/site_docs/summerbatch/docs/v_1-26/site/getting_started_summerbatchcore/getting_started.html).

The [sample project](https://github.com/SummerBatch/samples/tree/master/MyFirstBatchApplicationCore) also provides the SummerBatchCore version 

Best Regard
